version: "3.9"

services:
  flutter_web_app:
    image: ghcr.io/marekruttner/resolvei-application:latest
    container_name: flutter_web_app

    # Environment variables from .env
    environment:
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}

    # Publish port 80 inside the container as 20006 on the host
    ports:
      - "20006:80"

    networks:
      - proxy

    # Traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # HTTP router: redirect to HTTPS
      - "traefik.http.routers.flutter_web_app_http.entrypoints=web"
      - "traefik.http.routers.flutter_web_app_http.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.flutter_web_app_http.middlewares=redirect-to-https"

      # HTTPS router
      - "traefik.http.routers.flutter_web_app_https.entrypoints=websecure"
      - "traefik.http.routers.flutter_web_app_https.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.flutter_web_app_https.tls=true"
      - "traefik.http.routers.flutter_web_app_https.tls.certresolver=main-resolver"
      - "traefik.http.services.flutter_web_app_https.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
    name: traefik_proxy
