name: Build and Push Flutter Web to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # 1) Grab just the repo name (e.g. "myrepo" from "myorg/myrepo")
    #    using github.event.repository.name
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ghcr.io/${{ secrets.GHCR_USER }}/${{ env.REPO_NAME }}:${{ github.sha }} \
            --tag ghcr.io/${{ secrets.GHCR_USER }}/${{ env.REPO_NAME }}:latest \
            .

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USER }}/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USER }}/${{ env.REPO_NAME }}:latest
