name: Build and Push Flutter Web to GHCR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read   # needed to read code
  packages: write  # required for pushing to GHCR

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # We'll set REPO_NAME via github.event.repository.name
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      # 1) Check out code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3) Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4) Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 5) Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6) Build & Push Docker image using Buildx
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          # Build context: current directory
          context: .
          # Dockerfile name/location (if your file is named "Dockerfile" at the repo root, omit this):
          #   dockerfile: ./some-path/Dockerfile

          # Platforms to build for. By default, just linux/amd64:
          platforms: linux/amd64

          # Actually push the image to GHCR
          push: true

          # Provide one or more tags. We reference our env.REPO_NAME
          # and build two tags: one with the commit SHA, one "latest".
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
